### ISSUE TITLE
openwrt 22.03 not work

### ISSUE THREAD

**Issue by lencil** [starsunyzl/ddns-scripts-alibabacloud#1]
test in openwrt 22.03 rc6

**Comment by starsunyzl** [comment]
Please provide more information, your ddns-scripts version and log etc.

I've been running OpenWrt 22.03 rc5 for a while and just tested OpenWrt 22.03 stable, all works fine.

**Comment by lencil** [comment]
when add service, a warning showed up. 
"选项“名称”包含无效的输入值。 The service name is already used"

ddns-scripts - 2.8.2-25
ddns-scripts-services - 2.8.2-25

**Comment by starsunyzl** [comment]
It is a bug of ddns-scripts itself. Adding any service will report that error, even if this plugin is not installed. But no problem, the plugin will still work properly.

Tested on OpenWrt 22.03 stable + ddns-scripts 2.8.2-25
